### PR TITLE
BBCodes are now hardcoded in Subs-BBC again.

### PR DESCRIPTION
**Pull request by C3realGuy**
Still loading bbcodes from plugins from database.
Should increase performance.

### CODE REVIEW

**Comment by C3realGuy** [comment]
Only tried it on my local test install but didn't notice any issues.

**Comment by Nao** [comment]
I'm gonna merge to make your life easier. ;)
There are still spacinazis to fix though!

**Comment by Nao** [comment]
(And would be good if someone benchmarked both versions!)

**Comment by Nao** [comment]
I was doing the spacinazi thing when it hit me... you're using php7-specific array representations lol.
I'll need to fix those as well.

**Comment by Nao** [comment]
Or maybe I could use loadSource to change those on the fly depending on the php version...

**Pull request merged**
