### PR TITLE
Long [code][/code] tags and other content could break out of the

### PR DESCRIPTION
**Pull request by C3realGuy**
postarea div. Fixed with setting width of .posteare to 75%.

### CODE REVIEW

**Comment by Nao** [comment]
Hmm, isn't this a hack? Hard coding some random width means it only fixes one instance of the problem, not all. .

**Comment by C3realGuy** [comment]
I don't really know much about CSS so I can't provide a better solution.
Anyway i'm using this fix in a custom skin since some months and never ever saw overflowing content or any other layout bugs with this fix.
What I stumbled across was that setting .posteare width below 75% doesn't make a difference. So 75% is the lowest value you can set. Maybe this helps.

**Comment by nsgomez** [comment]
In Google Chrome 51.0.2704.106, setting the width of the postarea to 0 also limits the element to the bounds of the container, so it may not be necessary to specify a width of 75%. I haven't tested this with any other browsers, though.

**Comment by Nao** [comment]
That would be a good starting point to test, though. A width of '0'
probably triggers some other resizing internally, and if it's supported in
Firefox and IE 10 or above (don't care about the rest), then it's the right
way to do it.
:)
Can you look into it?

2016-07-18 16:09 GMT+02:00 Nelson Gomez <notifications@github.com>:

**Comment by nsgomez** [comment]
@Nao @C3realGuy Just did some tests and width: 0 for .postarea works fine in IE9+, Firefox 45, Chrome, Safari 5.1 and Opera 36 from what I can tell.

**Comment by C3realGuy** [comment]
Setting width: inherit is doing it for me too. I have no idea which way is the best, changed it to the solution by @nsgomez, looked best for me.

**Comment by Nao** [comment]
@C3realGuy, who the heck is CiderJack..? I'm seeing him in the commit log, not you?
As for width: inherit, it seems even better than 0 :-P Then again, it probably also compresses less than 0, so I'd be inclined to go for '0' and just forget about it. Also, 'inherit' makes me think that unless this width property was overriding something from earlier in the cascade, just removing the width line entirely would also fix it... ^^

@nsgomez, nice low-poly avatar. Did you make it yourself, or is there some online tool available to make those..? (Also... Always nice to see a Wedge user ;))

**Comment by C3realGuy** [comment]
@Nao no idea who CiderJack is, but this is because i didn't set a email address on my local git config. Don't ask me why it's not just using my github username/address...

**Comment by Nao** [comment]
So, is this name your nickname in some respect, but unrelated to the account identified by GH..?

**Comment by C3realGuy** [comment]
No, completely unrelated. Didn't set GIT_AUTHOR_NAME nor GIT_AUTHOR_EMAIL. That's causing the trouble. I'm going to change the commits.

**Comment by C3realGuy** [comment]
At least the user name and email should be correct. Bad commit history, don't merge this PR, better just commit the changes on your own. Otherwise I have to open a new PR or do some rebase stuff.

**Comment by nsgomez** [comment]
I've opened pull request #35 to keep the fixed commit history while getting rid of the merge messages, so it'd be easier to merge that.

**Pull request closed without merging**
