### PR TITLE
prevent race conditions by flocking files on loadSource()

### PR DESCRIPTION
**Pull request by C3realGuy**

### CODE REVIEW

**Comment by C3realGuy** [comment]
@Nao i'm not really happy with the variable name of $should_cache, maybe you have a better idea. Besides that using loadSource('Subs-CachePHP') is a bit useless and in my opinion dirty (also not really performant). I would consider to just require_once it? Also makes clear that this file never get's through any caching process.

**Comment by Nao** [comment]
That seems a bit overkill to me. Plus I'd rather keep index.php as short as possible.

I'd suggest instead to move the logic to Subs-CachePHP, and write the file to TheFileName-RandomNumber.php, then when it's over, rename(TheFileName-RandomNumber, TheFileName), this should act as some sort of flock to me... No? Plus we can even get rid of the actual flock in the current code.

**Comment by C3realGuy** [comment]
Hmm that's an idea. It's not really flocking but could solve the problem. And would be more performant as we don't need to fopen every file.
But we need to take care of race conditions again in Subs-CachePHP. I will give it a try.

**Comment by Nao** [comment]
I don't really see the possibility of a race condition if you attribute it a random number.
Basically, Wedge would be creating ViewRemote-212321334564564.php and ViewRemote-567354132324323.php at the same time, then renaming the first one to ViewRemote.php, then later renaming the second one (which has the same contents) to ViewRemote.php.

**Comment by C3realGuy** [comment]
I see a race condition when we want to cache a file at the same time. 
thread#1 file does not exist, let's cache!
thread#2 file does ................................!
thread#1 create file FileName-29120938.php
thread#2 create file FileName-21891898.php
thread#1 copy file content + minify
thread#2 copy file content + minify
thread#1 rename 
thread#2 rename... oups not working, file exists already

**Comment by Nao** [comment]
No no, it's working, rename() will delete the target file if it already
exists.
;)

2017-02-06 20:33 GMT+01:00 C3realGuy <notifications@github.com>:

**Comment by C3realGuy** [comment]
Good then this shouldn't be a problem. I will give it a try.

**Comment by C3realGuy** [comment]
No race conditions with rename() approach. After more than 2.5 years since reporting ^^

**Comment by Nao** [comment]
Lol!
I'll merge it then, so you'll have the pleasure of saying you fixed it. And I'll have the secret pleasure of saying I thought about renaming the file. :-D

**Pull request merged**
