### PR TITLE
Night Shift

### PR DESCRIPTION
**Pull request by French77**
Dark skin

### CODE REVIEW

**Comment by Nao** [comment]
Hmm...

1/ Screenshots please?
2/ Did you notice you actually deleted content from Wedge itself..? IE6/IE7 compatibility layers are useless these days, but I'd rather your don't delete them in my back... ^^
3/ If I merge this, I'll squash it because your git soup ("Merge branch..") entries are useless to users...  Well who cares, I'm just saying.
4/ Ahem, you also, ahem... Replaced a credit to me, with a credit for you... Okay... All right... Sure.

**Comment by Nao** [comment]
(You don't even have a proper thumbnail for the skin..?)

**Comment by French77** [comment]
Just an attempt to add new skins,no idea what the best way is.
if you can not use it, then don't used it !

This is the last time I make a request, it seems to me that you do not appreciate it

**Comment by French77** [comment]
> Thing is, I'm not forcing Wedge down anyone's throat-- it's up to you guys whether or not you want to contribute skins to it.
So do not ask for it anymore

**Comment by Nao** [comment]
Or you could just attach a zip file of your skin folder on a post in the
topic you mentioned. You obviously are having trouble with git itself and
it'd be simpler for everyone. Really no biggie...

**Pull request closed without merging**
