### PR TITLE
Improve validate function of bbc parsing for plugins and move bbc back to Subs-BBC

### PR DESCRIPTION
**Pull request by C3realGuy**
Many changes, it's not really tested yet, but still want to open the PR just so you can already have a look into it. If you want me to squash it into one commit i can rebase it.

### CODE REVIEW

**Comment by C3realGuy** [comment]
@Nao what do you think about splitting this into different PR's?
This got quite huge, i think it's better to merge it step by step.
So first would be to only merge the loadBBCodes() thing and removal
of the bbcodes from db. Next maybe the improvements for plugins.

**Comment by Nao** [comment]
I don't know, there are basically two portions here: Subs-BBC.php and the rest... I'm just not comfortable with either squashing these all together or merging them. It would be best if you squashed the related features together and we merged those squashes later on. Only I suck as doing squashing, rebasing, merging, all that crap... ^^

One of the things I'd like to point out is that you upgraded the database format, we should use the opportunity to remove unused fields from the database, e.g. the things I removed in a recent commit for install.sql, as well as the other most_* fields that are still unused I believe. (These came from Noisen.com related code, giving me very specific stats per-blog. But I don't think these will ever be used anywhere else, so...)

**Comment by C3realGuy** [comment]
Will squash the features, guess i have to open up different prs for the features. But give me some time. I'm currently busy.

Understood, we can merge it in a dev branch or something so you can add your delete statements to upgrade.php.

**Comment by C3realGuy** [comment]
@Nao will close this, i will redo the changes. Next step is improving the validate function again and the general syntax of the 'validate_func'. After that plugin integration.

**Pull request closed without merging**
