### PR TITLE
Fixing SSL for Aeva Media

### PR DESCRIPTION
**Pull request by C3realGuy**

### CODE REVIEW

**Comment by Nao** [comment]
There's already a PROTOCOL constant defined to either http:// or https://... Can't we rely on it, instead of adding a <PROT> variable..?

I'm not too sure. Honestly, I've been out of the loop for a few months now, and it's hard to get back into it with so little motivation... :(

**Comment by C3realGuy** [comment]
My idea was that we maybe need it in JS too at one day. I prefer to have a bit more flexibility.

**Comment by Nao** [comment]
Okay, but why <PROT> and not <PROTOCOL> then..? It'd be more self-explained.

Also, you don't need to use parenthesis in the main ternary test, just sayin'.
And finally -- $_SERVER is a superglobal, so you don't need to declare it in the globals list.. ;)

**Comment by C3realGuy** [comment]
Thanks @Nao for the hints and tips :+1: 
But what do you mean with "parenthesis in the main ternary test"? Didn't get that one.

Still don't know if it would be better to just replace my solution with PROTOCOL...

**Pull request merged**
