### PR TITLE
Shorten statistic dls with CSS

### PR DESCRIPTION
**Pull request by C3realGuy**
statsbar is maybe a bad naming, couldn't think of any better.

### CODE REVIEW

**Comment by Nao** [comment]
Actually, the goal here was to save on bandwidth in case the most popular topics have very long titles... Unlikely, I know, but anyway.

Also, for a long time Wedge was compatible with oldIE and CSS support wasn't too good...

**Comment by C3realGuy** [comment]
Hmm but how else to fix this issue? Just shortening the string with php isn't a solution, often it destroys the positioning. Maybe doing both? Shortening with php for oldie and bandwidth, css for the good looking.

**Comment by Nao** [comment]
Why not. Also I think there's already a generic class for CSS cutting in wedge.... Can you check?

**Comment by C3realGuy** [comment]
Aah that would be nice. I will check for that.

**Comment by C3realGuy** [comment]
@Nao *bump*

**Comment by Nao** [comment]
Bump for what..?

2015-07-05 20:41 GMT+02:00 C3realGuy <notifications@github.com>:

**Comment by C3realGuy** [comment]
Have a look at the last commit.

**Comment by Nao** [comment]
Didn't we talk about having to find a class name, or something..?

2015-07-06 14:44 GMT+02:00 C3realGuy <notifications@github.com>:

**Comment by C3realGuy** [comment]
Yes we did, simply named it ".shorten". I put the general css class into index.css and dl.statsbar is inheriting all the properties of it plus it inherits everything of dl.stats. Perhaps you can check if that's the proper way? If there's a better solution, just tell me and i will try again :D
It works fine, it's only about the "right way".

**Pull request merged**
